---

- name: Write out Ansible hosts config
  copy:
    content: >
      {{ openshift_ansible_inventory
      |to_nice_yaml|regex_replace('<host-inserted-here>', inventory_hostname) }}
    dest: /etc/ansible/hosts

- name: k8s templated objects directory
  file:
    state: directory
    path: "{{ openshift_ansible_tmp }}"

- name: Generate SSH key
  command: ssh-keygen -b 2048 -t rsa -f /root/.ssh/id_rsa -q -N ""
  args:
    creates: /root/.ssh/id_rsa
